# ---Stage 1: Build Dependencies ---

FROM python:3.11-slim AS builder 

WORKDIR /build 

RUN python -m venv /opt/venv 

ENV PATH="/opt/venv/bin:$PATH"

COPY requirements.txt .

RUN pip install -r requirements.txt

# --- Stage 2: Image Build ---

FROM python:3.11-slim 

WORKDIR /voting_app_backend 

ENV PYTHONUNBUFFERED=1 \
    PYTHONWRITEBYTECODE=1 \
    PATH="/opt/venv/bin:$PATH" 

RUN addgroup --system appgroup && adduser --system --ingroup appgroup appuser && chown -R appuser:appgroup .

COPY --from=builder --chown=appuser:appgroup /opt/venv /opt/venv

COPY --chown=appuser:appgroup ./app ./app 

EXPOSE 8000

USER appuser

ENTRYPOINT [ "uvicorn" ]

CMD [ "app.main:app", "--host", "0.0.0.0", "--port", "8000" ]